### ISSUE TITLE
IndewxError : List assignement index out of range

### ISSUE THREAD

**Issue by Maleficent-Magik** [UsedDiscord/RPIZircord#3]
Exception in thread Thread-3:
Traceback (most recent call last):
  File "C:\Users\WindowsN\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "C:\Users\WindowsN\PycharmProjects\HastagSpot\venv\lib\site-packages\timeloop\job.py", line 19, in run
    self.execute(*self.args, **self.kwargs)
  File "C:\Users\WindowsN\PycharmProjects\HastagSpot\test1.py", line 38, in kill
    lines[0] = "" #1
IndexError: list assignment index out of range

**Comment by Maleficent-Magik** [comment]
f = open('file.txt', 'r+')
f.truncate(0) # need '0' when using r+

?

**Comment by Maleficent-Magik** [comment]
Fix en utilisant Cron
